services:
  osrsdata.api:
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: osrsdata-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=OSRSData
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: