// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OSRSData.DAL;

#nullable disable

namespace OSRSData.DAL.Migrations
{
    [DbContext(typeof(OSRSDbContext))]
    partial class OSRSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OSRSData.Core.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("LootRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Player")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LootRecordId")
                        .IsUnique();

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("OSRSData.Core.Entities.LootItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LootRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootRecordId");

                    b.ToTable("LootItems");
                });

            modelBuilder.Entity("OSRSData.Core.Entities.LootRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Kc")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TotalValue")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LootRecords");
                });

            modelBuilder.Entity("OSRSData.Core.Entities.LogEntry", b =>
                {
                    b.HasOne("OSRSData.Core.Entities.LootRecord", "LootRecord")
                        .WithOne()
                        .HasForeignKey("OSRSData.Core.Entities.LogEntry", "LootRecordId");

                    b.Navigation("LootRecord");
                });

            modelBuilder.Entity("OSRSData.Core.Entities.LootItem", b =>
                {
                    b.HasOne("OSRSData.Core.Entities.LootRecord", "LootRecord")
                        .WithMany("Items")
                        .HasForeignKey("LootRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootRecord");
                });

            modelBuilder.Entity("OSRSData.Core.Entities.LootRecord", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
